name: Security Scan with Trivy

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: read

jobs:
  scan-dependencies:
    name: Scan Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy FS scan (Dependencies)
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          exit-code: '1' 

  scan-docker:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    needs: scan-dependencies 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t my-app:${{ github.sha }} .
      - name: Run Trivy Image scan (Docker)
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'image'
          image-ref: 'my-app:${{ github.sha }}'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'